[2024-11-26 19:14:33,103: WARNING/MainProcess] /Users/samadhan/Desktop/projects/custom_db/pythonProject/rebbitma_cluster/rabbitmq_instances/.venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-11-26 19:14:33,125: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-11-26 19:14:33,126: WARNING/MainProcess] /Users/samadhan/Desktop/projects/custom_db/pythonProject/rebbitma_cluster/rabbitmq_instances/.venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-11-26 19:14:33,139: INFO/MainProcess] mingle: searching for neighbors
[2024-11-26 19:14:34,168: INFO/MainProcess] mingle: all alone
[2024-11-26 19:14:34,185: WARNING/MainProcess] /Users/samadhan/Desktop/projects/custom_db/pythonProject/rebbitma_cluster/rabbitmq_instances/.venv/lib/python3.12/site-packages/kombu/pidbox.py:72: UserWarning: A node named celery@Samadhans-MacBook-Pro.local is already using this process mailbox!

Maybe you forgot to shutdown the other node or did not do so properly?
Or if you meant to start multiple nodes on the same host please make sure
you give each node a unique node name!

  warnings.warn(W_PIDBOX_IN_USE.format(node=self))

[2024-11-26 19:14:34,190: INFO/MainProcess] celery@Samadhans-MacBook-Pro.local ready.
[2024-11-26 19:17:03,920: WARNING/MainProcess] /Users/samadhan/Desktop/projects/custom_db/pythonProject/rebbitma_cluster/rabbitmq_instances/.venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-11-26 19:17:03,931: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-11-26 19:17:03,931: WARNING/MainProcess] /Users/samadhan/Desktop/projects/custom_db/pythonProject/rebbitma_cluster/rabbitmq_instances/.venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-11-26 19:17:03,941: INFO/MainProcess] mingle: searching for neighbors
[2024-11-26 19:17:04,966: INFO/MainProcess] mingle: all alone
[2024-11-26 19:17:04,985: WARNING/MainProcess] /Users/samadhan/Desktop/projects/custom_db/pythonProject/rebbitma_cluster/rabbitmq_instances/.venv/lib/python3.12/site-packages/kombu/pidbox.py:72: UserWarning: A node named celery@Samadhans-MacBook-Pro.local is already using this process mailbox!

Maybe you forgot to shutdown the other node or did not do so properly?
Or if you meant to start multiple nodes on the same host please make sure
you give each node a unique node name!

  warnings.warn(W_PIDBOX_IN_USE.format(node=self))

[2024-11-26 19:17:04,987: INFO/MainProcess] celery@Samadhans-MacBook-Pro.local ready.
